
```{r}
library(sf)
library(tidyverse)
library(dplyr)
library(ggplot2)

```
```{r}
# please change this to your file path
boro <- st_read("//ad.ucl.ac.uk/homea/ucfnina/Downloads/dissertation/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp")%>%st_transform(., 27700)

boro_sf <- st_as_sf(boro)
```
```{r}
lsoa <- st_read("//ad.ucl.ac.uk/homea/ucfnina/Downloads/dissertation/statistical-gis-boundaries-london/ESRI/london_lsoa_shp/LSOA_2011_London_gen_MHW.shp")%>%
    st_transform(., 27700)

lsoa_sf <- st_as_sf(lsoa)

```



```{r}
zoopla <-  read_csv("//ad.ucl.ac.uk/homea/ucfnina/Downloads/dissertation/Zoopla_6_0822.csv")  
```


```{r}
count_cloumns1 <- sapply(zoopla,function(col)length(na.omit(col)))

print(count_cloumns1)
```



```{r}
zoopla_pionts <- zoopla %>%
  st_as_sf(., coords = c("lon", "lat"), crs = 27700) 

# Perform spatial join using st_intersects
zoopla_join <- st_join(zoopla_pionts, lsoa , join = st_intersects)

# Filter out points that are not within any polygon
zoopla_join <- zoopla_join[!is.na(zoopla_join$LAD11NM), ]
```



```{r}
# Summarize the spatial join result without modifying geometry
price <- zoopla_join %>%
  group_by(LAD11NM) %>%
  summarise(boro_price = mean(price_last, na.rm = TRUE),
            pre_price = mean(ifelse(pre == 1, price_last, NA), na.rm = TRUE),
            during_price = mean(ifelse(during == 1, price_last, NA), na.rm = TRUE),
            post_price = mean(ifelse(post == 1, price_last, NA), na.rm = TRUE),
            post1_price = mean(ifelse(post1 == 1, price_last, NA), na.rm = TRUE),
            post2_price = mean(ifelse(post2 == 1, price_last, NA), na.rm = TRUE))


```

```{r}
price_lsoa<-zoopla_join %>%
  group_by(LSOA11NM)%>%
  summarise(lsoa_price=mean(price_last,na.rm=TRUE),
            pre_price = mean(ifelse(pre == 1,price_last,NA),na.rm=TRUE),
            during_price = mean(ifelse(during == 1,price_last,NA),na.rm=TRUE),
            post_price = mean(ifelse(post == 1,price_last,NA),na.rm=TRUE),
            post1_price = mean(ifelse(post1 == 1,price_last,NA),na.rm=TRUE),
            post2_price = mean(ifelse(post2 == 1,price_last,NA),na.rm=TRUE),
            )
```

```{r}
price <- price %>%
  mutate(
    diff_pre_during = ((during_price - pre_price)/pre_price)*100,
    diff_during_post = ((post_price - during_price)/during_price)*100,
    diff_during_post1 = ((post1_price - during_price)/during_price)*100,
    diff_post1_post2 = ((post2_price - post1_price)/post1_price)*100
  )
```

```{r}
price_lsoa <- price_lsoa %>%
  mutate(
    diff_pre_during = ((during_price - pre_price)/pre_price)*100,
    diff_during_post = ((post_price - during_price)/during_price)*100,
    diff_during_post1 = ((post1_price - during_price)/during_price)*100,
    diff_post1_post2 = ((post2_price - post1_price)/post1_price)*100
  )
```

```{r}
price <- st_drop_geometry(price)
price_lsoa <- st_drop_geometry(price_lsoa)
```

```{r}
count_cloumns2 <- sapply(zoopla_join,function(col)length(na.omit(col)))

print(count_cloumns2)
```


```{r}
write.csv(price, "//ad.ucl.ac.uk/homea/ucfnina/Downloads/dissertation/boro_price.csv")
write.csv(price_lsoa, "//ad.ucl.ac.uk/homea/ucfnina/Downloads/dissertation/lsoa_price.csv")
```
```{r}
zoopla_join2 <- st_drop_geometry(zoopla_join)

write.csv(zoopla_join2, "//ad.ucl.ac.uk/homea/ucfnina/Downloads/dissertation/zoopla_join0822.csv", row.names = FALSE)
```


